services:
    postgresql:
        container_name: picker-service-postgresql
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        networks:
            - postgres
        restart: unless-stopped


networks:
    postgres:
        driver: bridge

volumes:
    postgres:
